// <auto-generated />
namespace MySmallBusiness.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class cambiotipostring : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cambiotipostring));
        
        string IMigrationMetadata.Id
        {
            get { return "201712132040375_cambio-tipo-string"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
